import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { logout } from '../services/auth';
import { getProfile } from '../services/provider';
import { Colors, card } from '../theme';

export default function ProfileScreen({ navigation }) {
  const [profile, setProfile] = useState(null);
  useFocusEffect(useCallback(() => { getProfile().then(setProfile).catch((error) => Alert.alert('Could not load profile', error.message)); }, []));
  const signOut = async () => { await logout(); navigation.reset({ index: 0, routes: [{ name: 'Login' }] }); };
  if (!profile) return <View style={styles.center}><ActivityIndicator color={Colors.primary} /></View>;
  return (
    <ScrollView contentContainerStyle={styles.page}>
      <Text style={styles.title}>Profile</Text>
      <View style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{profile.user?.name?.[0] || 'P'}</Text></View><Text style={styles.name}>{profile.user?.name || 'Service provider'}</Text><Text style={styles.phone}>{profile.user?.phone ? `+91 ${profile.user.phone}` : ''}</Text><View style={[styles.badge, profile.status === 'APPROVED' && styles.approvedBadge]}><Text style={[styles.badgeText, profile.status === 'APPROVED' && styles.approvedText]}>{profile.status === 'APPROVED' ? '✓ VERIFIED PARTNER' : profile.status}</Text></View><View style={styles.ratingRow}><View><Text style={styles.ratingValue}>★ {profile.stats?.averageRating || 'New'}</Text><Text style={styles.ratingLabel}>{profile.stats?.ratingCount || 0} ratings</Text></View><View style={styles.metricDivider} /><View><Text style={styles.ratingValue}>{profile.stats?.completedJobs || 0}</Text><Text style={styles.ratingLabel}>jobs completed</Text></View></View></View>
      <Text style={styles.label}>Services</Text><View style={styles.services}>{profile.services?.map((item) => <View key={item.categoryId} style={styles.service}><Text style={styles.serviceText}>{item.category.name}</Text></View>)}</View>
      <Text style={styles.detail}>City: {profile.city || 'Not set'}</Text><Text style={styles.detail}>Experience: {profile.experienceYears || 0} years</Text>
      <Text style={styles.label}>Customer reviews</Text>
      {profile.recentReviews?.map((item) => <View key={item.id} style={styles.review}><View style={styles.reviewHeader}><Text style={styles.reviewStars}>{'★'.repeat(item.rating)}{'☆'.repeat(5 - item.rating)}</Text><Text style={styles.reviewDate}>{item.completedAt ? new Date(item.completedAt).toLocaleDateString() : ''}</Text></View><Text style={styles.reviewService}>{item.serviceName}</Text><Text style={styles.reviewText}>{item.review || 'Customer left a rating.'}</Text><Text style={styles.reviewCustomer}>— {item.customer?.name || 'Customer'}</Text></View>)}
      {!profile.recentReviews?.length ? <Text style={styles.empty}>Your customer ratings will appear here after completed jobs.</Text> : null}
      <TouchableOpacity style={styles.edit} onPress={() => navigation.navigate('Onboarding')}><Text style={styles.editText}>Edit provider profile</Text></TouchableOpacity><TouchableOpacity style={styles.logout} onPress={signOut}><Text style={styles.logoutText}>Log out</Text></TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({ center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.background }, page: { flexGrow: 1, backgroundColor: Colors.background, paddingTop: 55, padding: 18, paddingBottom: 100 }, title: { fontSize: 25, fontWeight: '900' }, card: { ...card, alignItems: 'center', marginTop: 18 }, avatar: { width: 70, height: 70, borderRadius: 35, backgroundColor: Colors.secondaryLight, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: Colors.secondary, fontWeight: '900', fontSize: 30 }, name: { fontSize: 20, fontWeight: '900', marginTop: 10 }, phone: { color: Colors.muted, marginTop: 4 }, badge: { backgroundColor: Colors.warningLight, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, marginTop: 12 }, badgeText: { color: Colors.warning, fontWeight: '900', fontSize: 12 }, approvedBadge: { backgroundColor: Colors.successLight }, approvedText: { color: Colors.success }, ratingRow: { flexDirection: 'row', alignItems: 'center', gap: 28, marginTop: 18 }, ratingValue: { color: Colors.secondary, fontSize: 20, fontWeight: '900', textAlign: 'center' }, ratingLabel: { color: Colors.muted, fontSize: 10, textAlign: 'center', marginTop: 3 }, metricDivider: { width: 1, height: 35, backgroundColor: Colors.border }, label: { fontWeight: '900', marginTop: 22, marginBottom: 10 }, services: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, service: { backgroundColor: Colors.secondaryLight, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 }, serviceText: { color: Colors.secondary, fontWeight: '800' }, detail: { ...card, marginTop: 10, color: Colors.muted }, review: { ...card, marginBottom: 9 }, reviewHeader: { flexDirection: 'row', justifyContent: 'space-between' }, reviewStars: { color: Colors.warning, fontWeight: '900' }, reviewDate: { color: Colors.muted, fontSize: 11 }, reviewService: { fontWeight: '900', marginTop: 8 }, reviewText: { color: Colors.textSecondary, lineHeight: 19, marginTop: 5 }, reviewCustomer: { color: Colors.muted, fontSize: 11, marginTop: 7 }, empty: { color: Colors.muted, backgroundColor: Colors.white, borderRadius: 12, padding: 18, textAlign: 'center' }, edit: { backgroundColor: Colors.secondary, borderRadius: 12, padding: 15, alignItems: 'center', marginTop: 20 }, editText: { color: Colors.white, fontWeight: '900' }, logout: { padding: 15, alignItems: 'center', marginTop: 8 }, logoutText: { color: Colors.danger, fontWeight: '900' } });
